os: linux
dist: bionic
sudo: required
language: python

python:
    - "3.4"

env:
  matrix:
    - TESSERACT=3.05.02-3

before_install:
  - export TESSERACT_INSTALL=$HOME/.tesseract
  - export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
  - export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
  - wget -O - https://github.com/nijel/tesseract-ocr-build/releases/download/$TESSERACT/tesseract.tar.xz | tar -C $HOME -xJf -

install:
  - sudo apt update
  - sudo apt install -y tesseract-ocr libtesseract-dev libleptonica-dev libpython3-dev libzbar-dev
  - pip install pytest-cov coveralls
  - pip install Cython
  - pip install Pillow
  - pip install -r requirements.txt

script:
    - py.test --cov-report term-missing --cov=src 
    
branches:
  only:
    - master
after_success:
  - coveralls
